version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing dependencies (if any)"
  pre_build:
    commands:
      - echo "Restoring Nuget packages"
  build:
    commands:
      - echo "Building and publishing .Net core application"
      - dotnet publish -c Release -o out # publises the appln to an 'out' folder
  post_build:
    commands:
      - echo "Build and publish completed"

artifacts:
  files:
    - '**/*'
  base-directory: out
